# Generated by Django 3.0.2 on 2020-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0001_initial'),
        ('gatinho', '0004_auto_20200110_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatinho',
            name='cor',
        ),
        migrations.AddField(
            model_name='gatinho',
            name='cor_da_pele',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo'), ('LARANJA', 'laranja'), ('CINZA', 'cinza'), ('TRICOLOR', 'tricolor')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gatinho',
            name='dono',
            field=models.ManyToManyField(blank=True, to='dono.Dono'),
        ),
    ]
